### ISSUE TITLE
Intermittent problems extending thread menu on macOS

### ISSUE THREAD

**Issue by petebankhead** [qupath/log-viewer#70]
I am sometimes seeing exceptions arising from the log viewer in QuPath, which cause the log viewer to break completely. 
Alas, I can't easily reproduce them and I fear the source might lie buried deep in JavaFX.

I see many exceptions popping up in the following form:
```
16:14:34.637 [JavaFX Application Thread] [ERROR] q.l.g.QuPathUncaughtExceptionHandler - arraycopy: last destination index 470 out of bounds for int[469]
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 470 out of bounds for int[469]
	at java.base/java.lang.System.arraycopy(Native Method)
	at javafx.collections.transformation.FilteredList.addRemove(FilteredList.java:272)
	at javafx.collections.transformation.FilteredList.sourceChanged(FilteredList.java:143)
	at javafx.collections.transformation.TransformationList.lambda$getListener$0(TransformationList.java:105)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:327)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:71)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:246)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:210)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:200)
	at java.base/java.util.AbstractList.add(AbstractList.java:113)
	at qupath.ui.logviewer.ui.main.LogViewerModel.addLogMessage(LogViewerModel.java:72)
	at qupath.ui.logviewer.ui.main.LogViewerModel.lambda$addLogMessage$0(LogViewerModel.java:74)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
```

Here is a screenshot showing what happens when I try to resize it after the log: basically, it is unusable and QuPath needs restarted.

<img width="847" alt="broken-log-viewer" src="https://github.com/user-attachments/assets/1f1a5c85-0b30-4988-b612-85ec0e3bc4e5">

The most recent occurrence was when I switched to debug mode, before running some multithreaded code.

I'm not sure if it can be fixed at source, but maybe there could be a workaround (e.g. wrapping the most relevant code in a try/catch, and attempting to recover more gracefully).

**Comment by Rylern** [comment]
I was not able to reproduce the issue, even when logging 10000 messages in parallel at the same time.

From the stacktrace, it looks like the [`filteredLogs`](https://github.com/qupath/log-viewer/blob/3ae9f9225baa1b7f15328be33595bd68af9d02b3/logviewer-ui-main/src/main/java/qupath/ui/logviewer/ui/main/LogViewerModel.java#L27) `FilteredList` becomes in an illegal state after listening to the [`allLogs`](https://github.com/qupath/log-viewer/blob/3ae9f9225baa1b7f15328be33595bd68af9d02b3/logviewer-ui-main/src/main/java/qupath/ui/logviewer/ui/main/LogViewerModel.java#L26) `ObservableList`. This could be caused by an update to `allLogs` from a different thread than the JavaFX Application Thread, but this never happens, so I think it's a JavaFX bug. I didn't find anything relevant on Google.

I don't think wrapping the most relevant code in a try/catch would change anything, because it won't prevent `filteredLogs` from being in an illegal state, it will just silent it. But maybe I'm wrong, so you can try to put the [`allLogs.add(logMessage);`](https://github.com/qupath/log-viewer/blob/3ae9f9225baa1b7f15328be33595bd68af9d02b3/logviewer-ui-main/src/main/java/qupath/ui/logviewer/ui/main/LogViewerModel.java#L72) line in a try catch statement.

**Comment by petebankhead** [comment]
I think I've tracked down the source of the issue and can reproduce it. It is quite specific...

It occurs when 
* using macOS with the system menubar turned on
* logging at the debug level (at least, I couldn't reproduce it at the info level) - and setting the UI to display debug logs
* logging from a thread with a 'new' name, triggering a new `MenuItem` to be added

When these things are in place, the following QuPath script could consistently produce the exception.

```groovy
for (int i = 0; i < 10; i++) {
    String randomName = UUID.randomUUID().toString()
    new Thread(this::logSomething, randomName).start()
}
    
def logSomething() {
    getLogger().debug("Something")
}
```

Replacing all items in the thread menu with `setAll` seems to work around the issue (rather than using `add` for the missing item only). I couldn't reproduce it with the proposed workaround in https://github.com/qupath/log-viewer/pull/71
